### ISSUE TITLE
autolock time not selectable

### ISSUE THREAD

**Issue by qwert4u** [sebastienserre/connect-your-nuki-smartlock#2]
I cannot select a time... the times are not displayed

**Comment by sebastienserre** [comment]
![2024-08-24_20-00](https://github.com/user-attachments/assets/0cee635a-bdd7-4115-a972-bd5dc3d55a06)
I think I've reproduced, I will fix this is a soon release.

**Comment by sebastienserre** [comment]
fix by 1.3.13
